name: localbite
description: "LocalBite - discover local restaurants, save favourites and write reviews."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  firebase_auth: ^6.6.1
  firebase_core: ^4.14.0
  firebase_database: ^12.5.0
  flutter:
    sdk: flutter
  geolocator: ^14.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
