// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5NJ_agWaFj9pVDTiWZc_v6upqA_4ruM4',
    appId: '1:1047516109337:android:ebe9ba63c9045396302888',
    messagingSenderId: '1047516109337',
    projectId: 'localbite-6d8e8',
    databaseURL: 'https://localbite-6d8e8-default-rtdb.firebaseio.com',
    storageBucket: 'localbite-6d8e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOCZ2Kplrj0YZraH85Vao8pt1dMzaFrvg',
    appId: '1:1047516109337:ios:4e59cdde75b934a7302888',
    messagingSenderId: '1047516109337',
    projectId: 'localbite-6d8e8',
    databaseURL: 'https://localbite-6d8e8-default-rtdb.firebaseio.com',
    storageBucket: 'localbite-6d8e8.firebasestorage.app',
    iosBundleId: 'com.example.localbite',
  );
}
